### ISSUE TITLE
Suggested rules from Adguard English filter

### ISSUE THREAD

**Issue by Alex-302** [SlowMemory/List-KR#38]
Hi
I am Adguard filters developer.
We have a few rules for Korean sites:
```
m.comic.naver.com###adpostArea
yuncomics.com##.floating-banner
shencomics.com##.floating-banner
mlbpark.donga.com##div[class^="ad_con"]
||advod.smartmediarep.com^$third-party
```
anti-ad block
```
persnacons.tistory.com#@#.adsbygoogle
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=realhd.co.kr
```
Could you add them to your filter and I will remove them from our English.
Also, if you do not mind, I will add your filter to Adguard filters list:)

**Comment by SlowMemory** [comment]
Hi Alex,

Thank you for suggestions! 

For rules 1,2,3, they are already taken care by other element hiding rules in this filter.
For the rule 4, it seems to be originated from this thread: https://forum.adguard.com/index.php?threads/resolved-mlbpark-web-app-android-missed-banner.8681/#post-74357
I see that the rule 4 is to hide a blank area reported by a user in this thread. This seems to be not needed with this filter, as this filter will block a javascript (http://cad.donga.com/MLBPARK/mobile_bottom_coupang.js) that loads an iframe occupies that area.

Rules 5,6,7 are actually needed and I added them to this filter.

Regarding your last remark, I am happy to add it to Adguard fitlers list! It will be beneficial for those who use it with Android version which does not support custom filters subscription. 
I see you guys are already adding it to the iOS version (https://github.com/AdguardTeam/AdguardForiOS/issues/100) so I’ve created a new filter unbreak.txt which is supposed to serve as a supplement for extensions which does not support javascript injection rules. For example, I want to block a regional tracking script completely but this causes console errors in some websites. I want to handle those in a similar way ga.js is treated, but I can’t request to hardcode it to every other adblockers so I made an exception rule for it in [unbreak.txt](https://github.com/SlowMemory/List-KR/blob/master/unbreak.txt).

One reason I started this off is the lack of Korean filters in Adguard. It seems that you guys are maintaining some regional filters like Japanese, Turkish, etc. It’s not been long since I started this and I am not experienced as you guys. How about just taking this and making a new Korean filter based on it?

**Comment by Alex-302** [comment]
It is available now in Adguard for windows.
About trackers - we usually ignore console errors if the site is not broken.
>How about just taking this and making a new Korean filter based on it?

Do you mean make it like English - add Andguard Korean with links to your filter.txt, adblock-korea and our fixes?

**Comment by SlowMemory** [comment]
>It is available now in Adguard for windows.
Thanks! But please change the linked homepage to https://list-kr.github.io instead of the current https://github.com/SlowMemory/List-KR.
Also when adding it to Adguard iOS or the content blocker, please concatenate filter.txt and unbreak.txt as there are websites which would be broken with filter.txt alone.
>Do you mean make it like English - add Andguard Korean with links to your filter.txt, adblock-korea and our fixes?
like English in the sense that it is systematically developed by Adguard team.

**Comment by Alex-302** [comment]
1. It will be done
2. We don't understand Korean...

**Comment by SlowMemory** [comment]
Now filter.txt and unbreak.txt is unnecessarily concatenated in Adguard windows version. Is it possible to use filter.txt only?

**Comment by SlowMemory** [comment]
Ok, thanks!
